export const initialCities = [
  { id: 'mumbai', name: 'Mumbai', state: 'Maharashtra', isPopular: true },
  { id: 'delhi-ncr', name: 'Delhi-NCR', state: 'Delhi', isPopular: true },
  { id: 'bengaluru', name: 'Bengaluru', state: 'Karnataka', isPopular: true },
  { id: 'hyderabad', name: 'Hyderabad', state: 'Telangana', isPopular: true },
  { id: 'chennai', name: 'Chennai', state: 'Tamil Nadu', isPopular: true },
];

export const initialMovies = [
  {
    _id: 'm1',
    title: 'Dune: Part Two',
    description: 'Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family, facing a choice between the love of his life and the fate of the universe.',
    poster: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=800&auto=format&fit=crop&q=80',
    backdrop: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=1600&auto=format&fit=crop&q=80',
    trailerUrl: 'https://www.youtube.com/watch?v=Way9Dexny3w',
    duration: 166,
    language: 'English',
    genres: ['Sci-Fi', 'Adventure', 'Action'],
    certificate: 'UA',
    releaseDate: new Date('2026-03-01'),
    cast: ['Timothée Chalamet', 'Zendaya', 'Rebecca Ferguson', 'Javier Bardem'],
    director: 'Denis Villeneuve',
    rating: 8.8,
    status: 'NOW_SHOWING',
    formats: ['IMAX', '4DX', '2D'],
  },
  {
    _id: 'm2',
    title: 'Oppenheimer: Director’s Cut',
    description: 'The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb, presented in glorious IMAX 70mm remastered print.',
    poster: 'https://images.unsplash.com/photo-1440404653325-ab127d49abc1?w=800&auto=format&fit=crop&q=80',
    backdrop: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1600&auto=format&fit=crop&q=80',
    trailerUrl: 'https://www.youtube.com/watch?v=uYPbbksJxIg',
    duration: 180,
    language: 'English',
    genres: ['Biography', 'Drama', 'History'],
    certificate: 'A',
    releaseDate: new Date('2026-02-15'),
    cast: ['Cillian Murphy', 'Emily Blunt', 'Matt Damon', 'Robert Downey Jr.'],
    director: 'Christopher Nolan',
    rating: 8.9,
    status: 'NOW_SHOWING',
    formats: ['IMAX', '2D'],
  },
  {
    _id: 'm3',
    title: 'Interstellar: 10th Anniversary IMAX',
    description: 'When Earth becomes uninhabitable in the future, a farmer and ex-NASA pilot, Joseph Cooper, is tasked to pilot a spacecraft, along with a team of researchers, to find a new planet for humans.',
    poster: 'https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=800&auto=format&fit=crop&q=80',
    backdrop: 'https://images.unsplash.com/photo-1464802686167-b939a6910659?w=1600&auto=format&fit=crop&q=80',
    trailerUrl: 'https://www.youtube.com/watch?v=zSWdZVtXT7E',
    duration: 169,
    language: 'English',
    genres: ['Sci-Fi', 'Drama', 'Adventure'],
    certificate: 'UA',
    releaseDate: new Date('2026-03-10'),
    cast: ['Matthew McConaughey', 'Anne Hathaway', 'Jessica Chastain', 'Michael Caine'],
    director: 'Christopher Nolan',
    rating: 8.7,
    status: 'NOW_SHOWING',
    formats: ['IMAX', '4DX', '2D'],
  },
  {
    _id: 'm4',
    title: 'Cyberpunk: Neon Horizon',
    description: 'In a dystopian mega-city controlled by synthetic oligarchs, a rogue cyber-detective uncovers an existential secret hidden in the memory banks of an android martyr.',
    poster: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=800&auto=format&fit=crop&q=80',
    backdrop: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=1600&auto=format&fit=crop&q=80',
    trailerUrl: 'https://www.youtube.com/watch?v=sample-trailer',
    duration: 135,
    language: 'English',
    genres: ['Action', 'Sci-Fi', 'Thriller'],
    certificate: 'A',
    releaseDate: new Date('2026-03-20'),
    cast: ['Karl Urban', 'Florence Pugh', 'Hiroyuki Sanada'],
    director: 'Alex Garland',
    rating: 8.4,
    status: 'NOW_SHOWING',
    formats: ['IMAX', '3D', '2D'],
  },
  {
    _id: 'm5',
    title: 'The Dark Knight: Legacy',
    description: 'Batman ventures into Gotham’s underworld when a cryptic sadist leaves behind a trail of calculated clues, forcing the dark detective to forge unlikely alliances.',
    poster: 'https://images.unsplash.com/photo-1509347528160-9a9e33742cdb?w=800&auto=format&fit=crop&q=80',
    backdrop: 'https://images.unsplash.com/photo-1478760329108-5c3ed9d495a0?w=1600&auto=format&fit=crop&q=80',
    trailerUrl: 'https://www.youtube.com/watch?v=mqqft2x_Aa4',
    duration: 155,
    language: 'English',
    genres: ['Action', 'Crime', 'Drama'],
    certificate: 'UA',
    releaseDate: new Date('2026-03-12'),
    cast: ['Robert Pattinson', 'Zoë Kravitz', 'Paul Dano', 'Jeffrey Wright'],
    director: 'Matt Reeves',
    rating: 8.6,
    status: 'NOW_SHOWING',
    formats: ['IMAX', '4DX', '2D'],
  },
  {
    _id: 'm6',
    title: 'Kalki: Genesis 2898 AD',
    description: 'Set in a post-apocalyptic world in the year 2898 AD, people are awaiting the arrival of a divine avatar to end the dark reign of Supreme Yaskin.',
    poster: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&auto=format&fit=crop&q=80',
    backdrop: 'https://images.unsplash.com/photo-1514565131-fce0801e5785?w=1600&auto=format&fit=crop&q=80',
    trailerUrl: 'https://www.youtube.com/watch?v=kalki-genesis',
    duration: 181,
    language: 'Hindi',
    genres: ['Action', 'Sci-Fi', 'Fantasy'],
    certificate: 'UA',
    releaseDate: new Date('2026-03-05'),
    cast: ['Prabhas', 'Amitabh Bachchan', 'Kamal Haasan', 'Deepika Padukone'],
    director: 'Nag Ashwin',
    rating: 8.2,
    status: 'NOW_SHOWING',
    formats: ['3D', 'IMAX', '2D'],
  },
  {
    _id: 'm7',
    title: 'Gladiator II',
    description: 'Years after witnessing the death of Maximus at the hands of his uncle, Lucius must enter the Colosseum after the powerful emperors of Rome conquer his home.',
    poster: 'https://images.unsplash.com/photo-1563089145-599997674d42?w=800&auto=format&fit=crop&q=80',
    backdrop: 'https://images.unsplash.com/photo-1528722828814-77b9b83aafb2?w=1600&auto=format&fit=crop&q=80',
    trailerUrl: 'https://www.youtube.com/watch?v=4rgYUipGJNo',
    duration: 148,
    language: 'English',
    genres: ['Action', 'Drama', 'Adventure'],
    certificate: 'A',
    releaseDate: new Date('2026-03-18'),
    cast: ['Paul Mescal', 'Pedro Pascal', 'Denzel Washington', 'Connie Nielsen'],
    director: 'Ridley Scott',
    rating: 8.3,
    status: 'NOW_SHOWING',
    formats: ['IMAX', '2D'],
  },
  {
    _id: 'm8',
    title: 'Solaris Echo',
    description: 'A psychological voyage to a space station orbiting a mysterious ocean planet where scientists start seeing manifestations of their deepest memories and regrets.',
    poster: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&auto=format&fit=crop&q=80',
    backdrop: 'https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=1600&auto=format&fit=crop&q=80',
    trailerUrl: 'https://www.youtube.com/watch?v=solaris-echo',
    duration: 128,
    language: 'English',
    genres: ['Sci-Fi', 'Mystery', 'Drama'],
    certificate: 'UA',
    releaseDate: new Date('2026-04-10'),
    cast: ['Ryan Gosling', 'Ana de Armas', 'Mark Strong'],
    director: 'Denis Villeneuve',
    rating: 8.5,
    status: 'UPCOMING',
    formats: ['IMAX', '2D'],
  },
  {
    _id: 'm9',
    title: 'Spider-Man: Beyond the Spider-Verse',
    description: 'Miles Morales catapults across the Multiverse to unite with Gwen Stacy and a new team of Spider-People to face off with a villain more powerful than anything they have ever encountered.',
    poster: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=800&auto=format&fit=crop&q=80',
    backdrop: 'https://images.unsplash.com/photo-1635805737707-575885ab0820?w=1600&auto=format&fit=crop&q=80',
    trailerUrl: 'https://www.youtube.com/watch?v=beyond-spiderverse',
    duration: 140,
    language: 'English',
    genres: ['Animation', 'Action', 'Adventure'],
    certificate: 'U',
    releaseDate: new Date('2026-05-01'),
    cast: ['Shameik Moore', 'Hailee Steinfeld', 'Oscar Isaac', 'Daniel Kaluuya'],
    director: 'Joaquim Dos Santos',
    rating: 9.1,
    status: 'UPCOMING',
    formats: ['3D', 'IMAX', '2D', '4DX'],
  },
  {
    _id: 'm10',
    title: 'Chrono Rift',
    description: 'When quantum researchers accidentally rupture the flow of historical time, an elite temporal expedition must race against entropy to restore the chronological continuum.',
    poster: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&auto=format&fit=crop&q=80',
    backdrop: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=1600&auto=format&fit=crop&q=80',
    trailerUrl: 'https://www.youtube.com/watch?v=chrono-rift',
    duration: 132,
    language: 'English',
    genres: ['Sci-Fi', 'Thriller', 'Action'],
    certificate: 'UA',
    releaseDate: new Date('2026-06-15'),
    cast: ['Oscar Isaac', 'Cate Blanchett', 'Tom Hardy'],
    director: 'Guillermo del Toro',
    rating: 8.0,
    status: 'UPCOMING',
    formats: ['IMAX', '4DX'],
  },
];

export const initialCinemas = [
  {
    _id: 'c1',
    name: 'Cinevo Luxe IMAX & 4DX',
    city: 'mumbai',
    address: 'Grand Palladium Mall, Senapati Bapat Marg, Lower Parel',
    facilities: ['IMAX Laser', '4DX Dynamic Chairs', 'Dolby Atmos', 'Valet Parking', 'Gourmet Lounge'],
    screenNames: ['Screen 1 - IMAX Laser', 'Screen 2 - 4DX Ultra', 'Screen 3 - Luxe Premiere'],
  },
  {
    _id: 'c2',
    name: 'Cinevo Royale Oceanfront',
    city: 'mumbai',
    address: 'Juhu Tara Road, Opposite Sea Princess, Juhu',
    facilities: ['Dolby Atmos', 'Recliner Loungers', 'Artisan Dining', 'Seaside Terrace'],
    screenNames: ['Screen 1 - Dolby Atmos', 'Screen 2 - Recliner Suite'],
  },
  {
    _id: 'c3',
    name: 'Cinevo Sovereign IMAX Laser',
    city: 'delhi-ncr',
    address: 'Select Citywalk Mall, District Centre, Saket, New Delhi',
    facilities: ['IMAX with Laser', 'Dolby Atmos', 'VIP Recliners', 'Complimentary Popcorn Bar'],
    screenNames: ['Screen 1 - IMAX 70mm Laser', 'Screen 2 - Sovereign Gold'],
  },
  {
    _id: 'c4',
    name: 'Cinevo Atmos Horizon',
    city: 'delhi-ncr',
    address: 'Ambience Mall, NH-8, DLF Phase 3, Gurugram',
    facilities: ['4DX Motion', 'Dolby Atmos', 'Gourmet Kitchen', 'Parking'],
    screenNames: ['Screen 1 - Atmos Grand', 'Screen 2 - 4DX Arena'],
  },
  {
    _id: 'c5',
    name: 'Cinevo Sphere IMAX',
    city: 'bengaluru',
    address: 'Phoenix Marketcity, Whitefield Main Rd, Devasandra, Bengaluru',
    facilities: ['Dual 4K Laser IMAX', 'RGB Dolby Vision', 'Motorized Recliners', 'Craft Gelato'],
    screenNames: ['Screen 1 - IMAX Sphere', 'Screen 2 - Atmos Elite'],
  },
  {
    _id: 'c6',
    name: 'Cinevo Orion Luxe',
    city: 'bengaluru',
    address: 'Orion Gateway Mall, Brigade Gateway, Malleshwaram, Bengaluru',
    facilities: ['Dolby Atmos', 'Recliner Suites', 'EV Charging', 'Sky Bar'],
    screenNames: ['Screen 1 - Premiere', 'Screen 2 - Gold Class'],
  },
  {
    _id: 'c7',
    name: 'Cinevo Zenith Cineplex',
    city: 'hyderabad',
    address: 'Inorbit Mall, Mindspace, Hitec City, Hyderabad',
    facilities: ['IMAX Laser', 'Dolby Atmos 64-Channel', 'Recliner Comfort', 'Valet'],
    screenNames: ['Screen 1 - IMAX Zenith', 'Screen 2 - Studio 2'],
  },
  {
    _id: 'c8',
    name: 'Cinevo Banjara Grand',
    city: 'hyderabad',
    address: 'Road No. 1, Banjara Hills, Hyderabad',
    facilities: ['Dolby Atmos', 'Luxury Dining', 'Acoustic Wall Paneling'],
    screenNames: ['Screen 1 - Grand Hall', 'Screen 2 - Atmos Lounge'],
  },
  {
    _id: 'c9',
    name: 'Cinevo Palais Royale',
    city: 'chennai',
    address: 'Express Avenue Mall, Whites Road, Royapettah, Chennai',
    facilities: ['IMAX with Laser', 'Dolby Atmos', 'Premium Recliners', 'South Gourmet Bistro'],
    screenNames: ['Screen 1 - IMAX Royale', 'Screen 2 - Dolby Studio'],
  },
  {
    _id: 'c10',
    name: 'Cinevo Marina Bay',
    city: 'chennai',
    address: 'Phoenix Marketcity, Velachery Main Rd, Chennai',
    facilities: ['4DX Dynamic', 'Dolby Atmos', 'VIP Valet', 'Gourmet Concessions'],
    screenNames: ['Screen 1 - 4DX Bay', 'Screen 2 - Premier 2'],
  },
];

// Helper to generate realistic standard cinema seat layout
export function generateStandardSeatLayout() {
  const rows = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H'];
  const layout = [];

  rows.forEach((rowLetter, rowIndex) => {
    let category = 'REGULAR';
    let count = 12;

    if (rowLetter === 'A') {
      category = 'RECLINER';
      count = 8; // Wider luxury recliners
    } else if (rowLetter === 'B' || rowLetter === 'C' || rowLetter === 'D') {
      category = 'PREMIUM';
      count = 10;
    } else {
      category = 'REGULAR';
      count = 12;
    }

    for (let col = 1; col <= count; col++) {
      layout.push({
        seatId: `${rowLetter}${col}`,
        seatNumber: `${rowLetter}${col}`,
        row: rowLetter,
        column: col,
        category,
      });
    }
  });

  return layout;
}
